name: generate animation

on:
  schedule:
    - cron: "0 5 * * *" # Se ejecuta automáticamente todos los días a las 00:00 en Perú (UTC-5)
  workflow_dispatch: # Esto te permite entrar a Actions y darle al botón "Run workflow" cuando quieras
  push:
    branches:
      - main # CUALQUIER cambio que hagas en tu rama main actualizará la serpiente al instante

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: generate-snake-svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: HernanFx
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23272996&color_dots=%23161b22,%231b2c6e,%233a55b4,%236ca0e0,%23bfe3ff
           
      - name: push-snake-svg-to-output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
